Fix crash on unmapped key codes in onKeyEvent
Added a check to ignore unmapped key codes in onKeyEvent method to prevent crashes.

Game Genie (on Asus devices) may send invalid keycodes such as 851 or 861
during screen on/off events. This caused `Keyboard.onKeyEvent()` to index
`keys[keyCode]` out of bounds (`length=159, index=851`), leading to
`ArrayIndexOutOfBoundsException`.

#### Exception details
Extracted from a logcat generated with adb:
```
FATAL EXCEPTION: main
Process: com.winlator
java.lang.ArrayIndexOutOfBoundsException: length=159 index=851
    at com.winlator.xserver.Keyboard.onKeyEvent(Keyboard.java:104)
Caused by: android.view.KeyEvent-JNI: java.lang.IllegalArgumentException: Invalid keycode 851
```